base_config: configs/acoustic.yaml

raw_data_dir:
  - /home/hanmeng/DiffSinger/data/opencpop/raw
  - /home/hanmeng/DiffSinger/data_preprocess/man_singer_0_final
  - /home/hanmeng/DiffSinger/data_preprocess/man_singer_1_final

speakers:
  - opencpop
  - man1
  - man2

spk_ids: []
test_prefixes:
  - 2003000085
  - 2007000214
  - 2007000228
  - 2010000354
  - 2010000368

dictionary: dictionaries/opencpop-extension-mul.txt

binary_data_dir: data/binary

binarization_args:
  num_workers: 0

use_spk_id: true
num_spk: 3
use_energy_embed: false
use_breathiness_embed: false
use_key_shift_embed: false
use_speed_embed: false

augmentation_args:
  random_pitch_shifting:
    enabled: false
    range: [-5., 5.]
    scale: 1.0
  fixed_pitch_shifting:
    enabled: false
    targets: [-5., 5.]
    scale: 0.75
  random_time_stretching:
    enabled: false
    range: [0.5, 2.]
    domain: log  # or linear
    scale: 1.0

residual_channels: 512
residual_layers: 20

optimizer_args:
  lr: 0.0004
lr_scheduler_args:
  scheduler_cls: torch.optim.lr_scheduler.StepLR
  step_size: 50000
  gamma: 0.5
max_batch_frames: 80000
max_batch_size: 48
max_updates: 320000

num_valid_plots: 10
val_with_vocoder: true
val_check_interval: 2000
num_ckpt_keep: 5
permanent_ckpt_start: 200000
permanent_ckpt_interval: 40000
pl_trainer_devices: 'auto'
pl_trainer_precision: '32-true'
